const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const source = fs.readFileSync('sundo-component.js', 'utf8');
const context = { React:{createElement:()=>({})}, DCLogic:class { setState(p){ this.state={...(this.state||{}),...p}; } }, setTimeout, clearTimeout };
vm.createContext(context);
vm.runInContext(`${source}\n;globalThis.SundoComponent=Component;`, context);
const app = new context.SundoComponent();
const lunch = app.recipes['Turkey Bean Vegetable Pasta'];
const dinner = app.recipes['Turkey Chilli Loaded Potatoes'];
const lunchTotals = app.weeklyRecipeTotals(lunch);
const dinnerTotals = app.weeklyRecipeTotals(dinner);
const groceries = app.groceryFor().groups.flatMap((group) => group.items);
[lunch, dinner].forEach((recipe) => assert.strictEqual(app.weeklyRecipeTotals(recipe).occurrences, 5, `${app.recipeNameFor(recipe)} must occur five times`));
[lunchTotals, dinnerTotals].forEach((totals) => {
  assert.ok(totals.Gabriel.ingredients['Turkey mince'] > totals.Cynthia.ingredients['Turkey mince'], 'Gabriel needs the larger calculated turkey portion');
  assert.strictEqual(Math.round(totals.totalIngredients['Turkey mince']), Math.round((totals.Cynthia.ingredients['Turkey mince'] + totals.Gabriel.ingredients['Turkey mince']) * 5), 'weekly turkey must equal five calculated meals each');
});
const expectedTurkey = Math.ceil(lunchTotals.totalIngredients['Turkey mince'] + dinnerTotals.totalIngredients['Turkey mince']) + ' packs';
assert.ok(groceries.some((item) => item.n === 'Turkey mince' && item.q === expectedTurkey), 'cart must combine both calculated turkey batches');
assert.ok(app.prepSections.find((section) => section.id === 'mains').steps.join(' ').includes('75°C'), 'shared turkey prep must state the safe cooking temperature');
console.log('weekly turkey batches, calculated portions, and cart totals stay in sync');
