const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const source = fs.readFileSync('sundo-component.js', 'utf8');
const context = { React:{createElement:()=>({})}, DCLogic:class { setState(p){ this.state={...(this.state||{}),...p}; } }, setTimeout, clearTimeout };
vm.createContext(context);
vm.runInContext(`${source}\n;globalThis.SundoComponent=Component;`, context);
const app = new context.SundoComponent();
const week = app.buildWeek();
const activeMeals = ['Berry Protein Overnight Oats','Banana Protein Yogurt','Turkey Bean Vegetable Pasta','Turkey Chilli Loaded Potatoes','Cottage Cheese Berry Cup'];
['Breakfast','Snack','Lunch','Dinner','Dessert'].forEach((slot, index) => assert.deepStrictEqual(Array.from(week[slot]), Array(5).fill(activeMeals[index])));
const scheduled = app.slots.flatMap((slot) => week[slot]);
activeMeals.forEach((meal) => {
  assert.ok(app.recipes[meal], `${meal} needs a live recipe card`);
  assert.strictEqual(app.resolveRecipe(meal), meal, `${meal} must resolve directly`);
  assert.ok(app.recipes[meal].ingredients.length > 0 && app.recipes[meal].method.length > 0, `${meal} needs a self-contained recipe`);
});
const groceries = app.groceryFor().groups.flatMap((group) => group.items);
['Turkey mince', 'Cannellini beans', 'Kidney beans', 'Tomato passata', 'Chopped tomatoes'].forEach((name) => assert.ok(groceries.some((item) => item.n === name), `cart should include ${name}`));
assert.ok(app.recipeOrder.every((meal) => scheduled.includes(meal)), 'Recipes should show only the active plan');
assert.deepStrictEqual(Array.from(app.thisWeekMains()), Array.from(week.Lunch.concat(week.Dinner)), 'Home and See all must show the active main-meal order');
const prep = app.prepSections.map((section) => section.steps.join(' ')).join(' ').toLowerCase();
['berry protein overnight oats', 'turkey batch', 'pasta', 'chilli', '75°c'].forEach((detail) => assert.ok(prep.includes(detail), `prep must explain ${detail}`));
console.log('fresh shared-ingredient rest-of-week plan checks passed');
