const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const source = fs.readFileSync('sundo-component.js', 'utf8');
const boot = fs.readFileSync('boot-app.js', 'utf8');
const context = { React:{createElement:()=>({})}, DCLogic:class { setState(p){ this.state={...(this.state||{}),...p}; } }, setTimeout, clearTimeout };
vm.createContext(context);
vm.runInContext(`${source}\n;globalThis.SundoComponent=Component;`, context);
const app = new context.SundoComponent();
const pasta = app.weeklyRecipeTotals(app.recipes['Turkey Bean Vegetable Pasta']);
const snack = app.weeklyRecipeTotals(app.recipes['Banana Protein Yogurt']);
const cart = app.groceryFor().groups.flatMap((group) => group.items);
assert.strictEqual(pasta.occurrences, 5, 'pasta totals must cover all five scheduled lunches');
assert.ok(pasta.totalIngredients.Courgette > 4, 'courgettes must be accumulated across five lunches, not divided by the week twice');
assert.ok(snack.totalIngredients.Bananas > 18, 'bananas must be accumulated across five snacks, not divided by the week twice');
assert.match(cart.find((item) => item.n === 'Courgettes').q, /^\d+$/, 'shopping list must round whole courgettes to a readable count');
assert.match(cart.find((item) => item.n === 'Bananas').q, /^\d+$/, 'shopping list must round whole bananas to a readable count');
assert.ok(source.includes("const fmtIngredient = (v, unit)=>{ const n=Math.max(1,Math.ceil(v));"), 'recipe cards must label quantities with rounded household measures instead of decimals');
const activeRecipes = app.recipeOrder.map((name) => app.recipes[name]);
activeRecipes.forEach((recipe) => recipe.ingredients.forEach((ingredient) => {
  assert.ok(Number.isInteger(ingredient.q), `${ingredient.n} must use a whole-number amount`);
  if (ingredient.cat === 'veg') assert.ok(!['g','ml'].includes(ingredient.u), `${ingredient.n} must be bought by a piece, punnet, can, or cup`);
  if (ingredient.cat === 'sauce') assert.ok(['tsp','tbsp','cup','cups','can'].includes(ingredient.u), `${ingredient.n} must use a practical kitchen measure`);
}));
assert.ok(cart.every((item) => !/\d+\.\d/.test(item.q)), 'shopping list must never expose fractional quantities');
assert.ok(!source.includes("whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}},it.n"), 'cart names must not be ellipsized');
assert.ok(source.includes("calc(116px + env(safe-area-inset-bottom, 0px))"), 'Prep needs bottom clearance after expanded content');
assert.ok(boot.includes("calc(116px + env(safe-area-inset-bottom, 0px))"), 'Cart needs bottom clearance after its final item');
console.log('mobile readability, whole-produce labels, and five-day ingredient totals check passed');
