const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const source = fs.readFileSync('sundo-component.js', 'utf8');
const context = { React:{createElement:()=>({})}, DCLogic:class { setState(p){ this.state={...(this.state||{}),...p}; } }, setTimeout, clearTimeout };
vm.createContext(context);
vm.runInContext(`${source}\n;globalThis.SundoComponent=Component;`, context);
const app = new context.SundoComponent();
const lunch = app.recipes['Turkey Bean Vegetable Pasta'];
const dinner = app.recipes['Turkey Chilli Loaded Potatoes'];
const initialLunch = app.weeklyRecipeTotals(lunch);
const initialDinner = app.weeklyRecipeTotals(dinner);
assert.strictEqual(app.targetsFor(app.state.people.me).protein, 120, 'Cynthia target derives from her saved profile');
assert.strictEqual(app.targetsFor(app.state.people.partner).protein, 136, 'Gabriel target derives from his saved profile');
assert.strictEqual(initialLunch.Cynthia.protein, 30, 'Cynthia gets one quarter of her protein target at lunch');
assert.strictEqual(initialLunch.Gabriel.protein, 34, 'Gabriel gets one quarter of his protein target at lunch');
assert.ok(initialLunch.Gabriel.ingredients['Turkey mince'] > initialLunch.Cynthia.ingredients['Turkey mince'], 'Gabriel has the larger lunch turkey portion');
assert.ok(initialDinner.Gabriel.ingredients['Turkey mince'] > initialDinner.Cynthia.ingredients['Turkey mince'], 'Gabriel has the larger dinner turkey portion');
app.updatePerson('me', {weight:65});
const changedLunch = app.weeklyRecipeTotals(lunch);
const changedDinner = app.weeklyRecipeTotals(dinner);
assert.strictEqual(app.targetsFor(app.state.people.me).protein, 130, 'changing Cynthia weight recalculates her home target');
assert.strictEqual(changedLunch.Cynthia.protein, 33, 'changing Cynthia target recalculates her lunch protein share');
assert.ok(changedLunch.Cynthia.ingredients['Turkey mince'] > initialLunch.Cynthia.ingredients['Turkey mince'], 'Cynthia lunch turkey responds to profile changes');
assert.ok(changedDinner.Cynthia.ingredients['Turkey mince'] > initialDinner.Cynthia.ingredients['Turkey mince'], 'Cynthia dinner turkey responds to profile changes');
const expected = Math.round(changedLunch.totalIngredients['Turkey mince'] + changedDinner.totalIngredients['Turkey mince']) + ' g';
assert.strictEqual(app.groceryFor().groups.flatMap((group)=>group.items).find((item)=>item.n==='Turkey mince').q, expected, 'cart must use the changed combined turkey total');
console.log('profile-driven turkey portions and shopping totals stay in sync');
