const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const source = fs.readFileSync('sundo-component.js', 'utf8');
const context = { React:{createElement:()=>({})}, DCLogic:class { setState(p){this.state={...(this.state||{}),...p};} }, setTimeout, clearTimeout };
vm.createContext(context); vm.runInContext(`${source}\n;globalThis.SundoComponent=Component;`, context);
const app = new context.SundoComponent();
const lunch = app.recipes['Lemon Parsley Chicken Lentil Rice Bowls'];
const dinner = app.recipes['Red Lentil Spinach Curry'];
const initialLunch = app.weeklyRecipeTotals(lunch), initialDinner = app.weeklyRecipeTotals(dinner);
assert.strictEqual(app.targetsFor(app.state.people.me).protein,120);
assert.strictEqual(app.targetsFor(app.state.people.partner).protein,136);
assert.strictEqual(initialLunch.Cynthia.protein,30);
assert.strictEqual(initialLunch.Gabriel.protein,34);
assert.ok(initialLunch.Gabriel.ingredients['Chicken breast, raw']>initialLunch.Cynthia.ingredients['Chicken breast, raw']);
assert.ok(initialDinner.Gabriel.ingredients['Red lentils']>initialDinner.Cynthia.ingredients['Red lentils']);
app.updatePerson('me',{weight:65});
const changedLunch=app.weeklyRecipeTotals(lunch), changedDinner=app.weeklyRecipeTotals(dinner);
assert.strictEqual(app.targetsFor(app.state.people.me).protein,130);
assert.strictEqual(changedLunch.Cynthia.protein,33);
assert.ok(changedLunch.Cynthia.ingredients['Chicken breast, raw']>initialLunch.Cynthia.ingredients['Chicken breast, raw']);
assert.ok(changedDinner.Cynthia.ingredients['Red lentils']>initialDinner.Cynthia.ingredients['Red lentils']);
const expected=Math.ceil(changedLunch.totalIngredients['Chicken breast, raw'])+' g';
assert.strictEqual(app.groceryFor().groups.flatMap(group=>group.items).find(item=>item.n==='Chicken breast, raw').q,expected);
console.log('profile-driven chicken and curry portions and shopping totals stay in sync');
