const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const source = fs.readFileSync('sundo-component.js', 'utf8');
const swSource = fs.readFileSync('sw.js', 'utf8');
const context = { React:{createElement:()=>({})}, DCLogic:class { setState(p){ this.state={...(this.state||{}),...p}; } }, setTimeout, clearTimeout };
vm.createContext(context);
vm.runInContext(`${source}\n;globalThis.SundoComponent=Component;`, context);
const app = new context.SundoComponent();
const week = app.buildWeek();
const scheduled = app.slots.flatMap((slot)=>week[slot]);
assert.deepStrictEqual(Array.from(app.days.map((day)=>day.k)), ['Wed','Thu','Fri','Sat','Sun']);
app.slots.forEach((slot)=>assert.strictEqual(week[slot].length, 5, `${slot} needs five meals`));
assert.strictEqual(scheduled.length, 25, 'rest-week plan has all twenty-five meal slots');
assert.ok(app.recipeOrder.every((meal)=>scheduled.includes(meal)), 'Recipes only foregrounds active meals');
assert.deepStrictEqual(Array.from(app.thisWeekMains()), Array.from(week.Lunch.concat(week.Dinner)), 'Home and See all stay in active-main order');
const prep = app.prepSections.map((section)=>section.steps.join(' ')).join(' ').toLowerCase();
['salted date-and-banana chia pots','cinnamon-roll protein muffins','carrot-cake squares','turkey batch','pasta','chilli','75°c','freeze friday–sunday'].forEach((detail)=>assert.ok(prep.includes(detail), `prep needs ${detail}`));
assert.ok(source.includes("'WED–SUN · REST OF WEEK'"), 'Home header identifies the shortened plan');
assert.ok(swSource.includes("const CACHE = 'sundo-app-v28';"), 'service worker must refresh installed copies after the fresh-plan update');
console.log('fresh rest-of-week meal-prep checks passed');
