const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const source = fs.readFileSync('sundo-component.js', 'utf8');
const swSource = fs.readFileSync('sw.js', 'utf8');
const context = { React:{createElement:()=>({})}, DCLogic:class { setState(p){ this.state={...(this.state||{}),...p}; } }, setTimeout, clearTimeout };
vm.createContext(context);
vm.runInContext(`${source}\n;globalThis.SundoComponent=Component;`, context);
const app = new context.SundoComponent();
const week = app.buildWeek();
const scheduled = app.slots.flatMap((slot)=>week[slot]);
assert.deepStrictEqual(Array.from(app.days.map((day)=>day.k)), ['Wed','Thu','Fri']);
app.slots.forEach((slot)=>assert.strictEqual(week[slot].length, 3, `${slot} needs three meals`));
assert.strictEqual(scheduled.length, 12, 'rest-week plan has all twelve meal slots');
assert.ok(app.recipeOrder.every((meal)=>scheduled.includes(meal)), 'Recipes only foregrounds active meals');
assert.deepStrictEqual(Array.from(app.thisWeekMains()), Array.from(week.Lunch.concat(week.Dinner)), 'Home and See all stay in active-main order');
const prep = app.prepSections.map((section)=>section.steps.join(' ')).join(' ').toLowerCase();
['six pumpkin protein overnight oats','18 cottage cheese protein balls','bulgogi','rice soup','75°c','freeze friday'].forEach((detail)=>assert.ok(prep.includes(detail), `prep needs ${detail}`));
assert.ok(source.includes("'WED–FRI · REST OF WEEK'"), 'Home header identifies the shortened plan');
assert.ok(swSource.includes("const CACHE = 'sundo-app-v19';"), 'service worker must refresh installed copies after the new menu');
console.log('rest-of-week inbox-based meal-prep checks passed');
