const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const source = fs.readFileSync('sundo-component.js', 'utf8');
const context = { React:{createElement:()=>({})}, DCLogic:class { setState(patch) { this.state = { ...(this.state || {}), ...patch }; } }, setTimeout, clearTimeout };
vm.createContext(context);
vm.runInContext(`${source}\n;globalThis.SundoComponent=Component;`, context);
const app = new context.SundoComponent();
const lunch = app.weeklyRecipeTotals(app.recipes['Turkey Bean Vegetable Pasta']);
const dinner = app.weeklyRecipeTotals(app.recipes['Turkey Chilli Loaded Potatoes']);
const expectedRaw = lunch.totalIngredients['Turkey mince'] + dinner.totalIngredients['Turkey mince'];
const groceries = app.groceryFor().groups.flatMap((group) => group.items);
assert.strictEqual(Math.ceil(expectedRaw) + ' packs', groceries.find((item) => item.n === 'Turkey mince').q, 'shared turkey grocery total must equal both scheduled recipes combined');
assert.ok(lunch.Cynthia.ingredients['Turkey mince'] < lunch.Gabriel.ingredients['Turkey mince'], 'lunch uses distinct profile-driven portions');
assert.ok(dinner.Cynthia.ingredients['Turkey mince'] < dinner.Gabriel.ingredients['Turkey mince'], 'dinner uses distinct profile-driven portions');
const mains = app.prepSections.find((section) => section.id === 'mains').steps.join(' ');
assert.ok(mains.includes('shared turkey') && mains.includes('75°C'), 'Sunday prep must make the safe shared turkey batch discoverable');
assert.ok(app.prepSections.find((section) => section.id === 'store').steps.join(' ').includes('Freeze Friday–Sunday'), 'storage guide must cover the full remaining week');
console.log('shared turkey batch prep stays allocated across lunch and dinner');
