const assert=require('assert'),fs=require('fs'),vm=require('vm');
const source=fs.readFileSync('sundo-component.js','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const context={React:{createElement:()=>({})},DCLogic:class {setState(p){this.state={...(this.state||{}),...p}}},setTimeout,clearTimeout};
vm.createContext(context);vm.runInContext(`${source}\n;globalThis.App=Component;`,context);
const app=new context.App(), week=app.buildWeek();
assert.deepStrictEqual(Array.from(app.days.map(d=>d.k)),['Wed','Thu','Fri']);
app.slots.forEach(slot=>assert.strictEqual(week[slot].length,3));
const cake=app.weeklyRecipeTotals(app.recipes['High-Protein Carrot Cake Squares']);
const lunch=app.weeklyRecipeTotals(app.recipes['Turkey Bean Vegetable Pasta']);
const dinner=app.weeklyRecipeTotals(app.recipes['Turkey Chilli Loaded Potatoes']);
assert.strictEqual(cake.occurrences,3); assert.strictEqual(Math.round(cake.totalIngredients.Eggs),3);
assert.strictEqual(Math.round(lunch.totalIngredients['Turkey mince']+dinner.totalIngredients['Turkey mince']),1650);
const cart=app.groceryFor().groups.flatMap(g=>g.items);
assert.ok(cart.some(x=>x.n==='Eggs'&&x.q==='6'));assert.ok(cart.some(x=>x.n==='Turkey mince'&&x.q==='1650 g'));
assert.strictEqual(app.groceryFor().label,'Wednesday–Friday Meal Prep');
assert.ok(app.prepSections.find(x=>x.id==='store').steps.join(' ').includes('Wednesday–Friday portions'));
assert.ok(sw.includes("const CACHE = 'sundo-app-v36';"));
console.log('Wednesday–Friday batches, cart, and storage are synchronized');
